language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

  
    # Specify at least one system image,
    # if you need to run emulator(s) during your testss
     - sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-17

before_install:
 - chmod +x gradlew

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

#script:
#  - android list target
#  - ./gradlew build connectedCheck --stacktrace --info
#  - chmod +x ./gradlew
